# Generated by Django 6.1.1 on 2026-09-30 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField(default=0)),
                ('image_back', models.URLField(blank=True, max_length=400)),
                ('image_front', models.URLField(blank=True, max_length=400)),
                ('group', models.CharField(db_index=True, default='main', max_length=64)),
                ('is_bonus', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['price', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('percent', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('max_uses', models.PositiveIntegerField(default=0)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('prize_pool', models.PositiveIntegerField(default=0)),
                ('entry_fee', models.PositiveIntegerField(default=0)),
                ('max_players', models.PositiveIntegerField(default=64)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('is_open', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['starts_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
                ('wagered', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=32, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('weapon', models.CharField(blank=True, max_length=100)),
                ('finish', models.CharField(blank=True, max_length=100)),
                ('price', models.PositiveIntegerField(default=0)),
                ('image_url', models.URLField(max_length=400)),
            ],
            options={
                'ordering': ['price', 'name'],
                'indexes': [models.Index(fields=['price'], name='cases_skin_price_a61543_idx')],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('consumed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL)),
                ('skin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.skin')),
            ],
            options={
                'ordering': ['-acquired_at'],
            },
        ),
        migrations.CreateModel(
            name='Giveaway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('prize', models.CharField(max_length=160)),
                ('entry_price', models.PositiveIntegerField(default=0)),
                ('winner_name', models.CharField(blank=True, max_length=150)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giveaway_wins', to=settings.AUTH_USER_MODEL)),
                ('prize_skin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.skin')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GiveawayEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('giveaway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='cases.giveaway')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('giveaway', 'user')},
            },
        ),
        migrations.CreateModel(
            name='PromoUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uses', to='cases.promo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('promo', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Drop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=150)),
                ('price', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.case')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('skin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.skin')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='cases_drop_created_676fe9_idx'), models.Index(fields=['-price'], name='cases_drop_price_021483_idx')],
            },
        ),
        migrations.CreateModel(
            name='CaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=6, default=1, max_digits=12)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cases.case')),
                ('skin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.skin')),
            ],
            options={
                'indexes': [models.Index(fields=['case'], name='cases_casei_case_id_23dbc6_idx')],
                'unique_together': {('case', 'skin')},
            },
        ),
    ]
